export type GlyphName =
  | 'member'
  | 'ceo'
  | 'crm'
  | 'faults'
  | 'payment'
  | 'wordpress'
  | 'updates'
  | 'auth'
  | 'integrations'
  | 'projects'
  | 'default'

export function getNavigationGlyphName(pathname: string): GlyphName {
  if (pathname.startsWith('/member')) return 'member'
  if (pathname.startsWith('/ceo')) return 'ceo'
  if (pathname.startsWith('/crm')) return 'crm'
  if (pathname.startsWith('/faults')) return 'faults'
  if (pathname.startsWith('/payment')) return 'payment'
  if (pathname.startsWith('/wordpress')) return 'wordpress'
  if (pathname.startsWith('/updates')) return 'updates'
  if (pathname.startsWith('/integrations')) return 'integrations'
  if (pathname.startsWith('/auth')) return 'auth'
  if (pathname.startsWith('/projects') || pathname.startsWith('/boards')) return 'projects'
  return 'default'
}
