export type GlyphName =
  | 'member'
  | 'ai'
  | 'ceo'
  | 'crm'
  | 'faults'
  | 'payment'
  | 'wordpress'
  | 'updates'
  | 'auth'
  | 'integrations'
  | 'projects'
  | 'cognilabsai-chat'
  | 'cognilabsai-integrations'
  | 'audit'
  | 'attendance'
  | 'default'

export function getNavigationGlyphName(pathname: string): GlyphName {
  if (pathname.startsWith('/member/attendance')) return 'attendance'
  if (pathname.startsWith('/member')) return 'member'
  if (pathname.startsWith('/ceo/ai')) return 'ai'
  if (pathname.startsWith('/ceo/attendance')) return 'attendance'
  if (pathname.startsWith('/ceo')) return 'ceo'
  if (pathname.startsWith('/crm')) return 'crm'
  if (pathname.startsWith('/faults')) return 'faults'
  if (pathname.startsWith('/payment')) return 'payment'
  if (pathname.startsWith('/wordpress')) return 'wordpress'
  if (pathname.startsWith('/updates')) return 'updates'
  if (pathname.startsWith('/cognilabsai/chat')) return 'cognilabsai-chat'
  if (pathname.startsWith('/cognilabsai/integrations')) return 'cognilabsai-integrations'
  if (pathname.startsWith('/audit')) return 'audit'
  if (pathname.startsWith('/integrations')) return 'integrations'
  if (pathname.startsWith('/auth')) return 'auth'
  if (pathname.startsWith('/projects') || pathname.startsWith('/boards')) return 'projects'
  return 'default'
}
