export const navigationItems = [
  {
    to: '/overview',
    label: 'Overview',
    description: 'Project status, arxitektura va modul xaritasi.',
    group: 'Core',
    sidebar: true,
    permissionKey: undefined,
    defaultRedirect: false,
  },
  {
    to: '/auth/login',
    label: 'Auth',
    description: 'Login, register va recovery flow tayyor.',
    group: 'Access',
    sidebar: false,
    permissionKey: undefined,
    defaultRedirect: false,
  },
  {
    to: '/ceo/dashboard',
    label: 'CEO Dashboard',
    description: 'CEO statistik kartalari va daily metrics.',
    group: 'CEO',
    permissionKey: 'ceo',
    sidebar: true,
    defaultRedirect: true,
  },
  {
    to: '/ceo/users',
    label: 'Users & Permissions',
    description: 'User management va permission overview.',
    group: 'CEO',
    permissionKey: 'ceo',
    sidebar: true,
    defaultRedirect: false,
  },
  {
    to: '/crm',
    label: 'CRM',
    description: 'Customers, filters, statuses va sales stats.',
    group: 'Sales',
    permissionKey: 'crm',
    sidebar: true,
    defaultRedirect: true,
  },
  {
    to: '/finance',
    label: 'Finance',
    description: 'Finance dashboard, list, balances va exchange rate.',
    group: 'Finance',
    permissionKey: 'finance_list',
    sidebar: true,
    defaultRedirect: true,
  },
  {
    to: '/updates',
    label: 'Updates',
    description: 'Update tracking, recent, missing va company stats.',
    group: 'People',
    permissionKey: 'update_list',
    sidebar: true,
    defaultRedirect: true,
  },
] as const
