export const navigationItems = [
  {
    to: '/auth/login',
    label: 'Auth',
    description: 'Login, register va recovery flow tayyor.',
    group: 'Access',
    sidebar: false,
    permissionKey: undefined,
    defaultRedirect: false,
  },
  {
    to: '/ceo/dashboard',
    label: 'CEO Dashboard',
    description: 'CEO statistik kartalari va daily metrics.',
    group: 'CEO',
    permissionKey: 'ceo',
    sidebar: true,
    defaultRedirect: true,
  },
  {
    to: '/ceo/users',
    label: 'Users & Permissions',
    description: 'User management va permission overview.',
    group: 'CEO',
    permissionKey: 'ceo',
    sidebar: true,
    defaultRedirect: false,
  },
  {
    to: '/ceo/team-updates',
    label: 'Team Monthly Updates',
    description: 'Monitor employee update activity by month.',
    group: 'CEO',
    permissionKey: 'ceo',
    sidebar: true,
    defaultRedirect: false,
  },
  {
    to: '/crm',
    label: 'CRM',
    description: 'Customers, filters, statuses va sales stats.',
    group: 'Sales',
    permissionKey: 'crm',
    sidebar: true,
    defaultRedirect: true,
  },
  {
    to: '/faults',
    label: 'Faults',
    description: 'System faults, incidents va API holati.',
    group: 'CEO',
    permissionKey: 'ceo',
    sidebar: true,
    defaultRedirect: false,
  },
  {
    to: '/updates',
    label: 'Updates',
    description: 'Update tracking, recent, missing va company stats.',
    group: 'People',
    permissionKey: 'update_list',
    sidebar: true,
    defaultRedirect: true,
  },
] as const
